//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Данные_пользователя
    {
        public int ID { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<int> ID_пользователя { get; set; }
        public Nullable<System.DateTime> Последняя_дата_входа { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
    }
}
