//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ_Товар
    {
        public int ID { get; set; }
        public Nullable<int> ID_заказа { get; set; }
        public Nullable<int> ID_товара { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
