//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.Заказ_Товар = new HashSet<Заказ_Товар>();
        }
    
        public int ID { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Вид_товара { get; set; }
        public Nullable<int> Количество_на_складе { get; set; }
        public Nullable<int> Цена { get; set; }
        public byte[] Изображение { get; set; }
    
        public virtual Вид_товара Вид_товара1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ_Товар> Заказ_Товар { get; set; }
    }
}
